export const CATEGORIES = [
  "fashion",
  "beauty",
  "electronics",
  "home-garden",
  "food-beverage",
  "health-wellness",
  "sports-outdoors",
  "pets",
  "kids-baby",
  "jewelry",
  "automotive",
  "arts-crafts",
  "books-media",
  "business-services",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_LABELS: Record<Category, string> = {
  fashion: "Fashion & Apparel",
  beauty: "Beauty & Cosmetics",
  electronics: "Electronics & Tech",
  "home-garden": "Home & Garden",
  "food-beverage": "Food & Beverage",
  "health-wellness": "Health & Wellness",
  "sports-outdoors": "Sports & Outdoors",
  pets: "Pets",
  "kids-baby": "Kids & Baby",
  jewelry: "Jewelry & Accessories",
  automotive: "Automotive",
  "arts-crafts": "Arts & Crafts",
  "books-media": "Books & Media",
  "business-services": "Business Services",
  other: "Other",
};

export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  fashion: [
    "clothing",
    "apparel",
    "dress",
    "shirt",
    "pants",
    "shoes",
    "sneakers",
    "fashion",
    "wear",
    "outfit",
    "jacket",
    "hoodie",
    "t-shirt",
    "jeans",
    "skirt",
  ],
  beauty: [
    "skincare",
    "makeup",
    "cosmetic",
    "beauty",
    "serum",
    "cream",
    "lotion",
    "fragrance",
    "perfume",
    "hair care",
    "nail",
    "lipstick",
  ],
  electronics: [
    "electronic",
    "phone",
    "laptop",
    "computer",
    "gadget",
    "cable",
    "charger",
    "speaker",
    "headphone",
    "camera",
    "tech",
    "smart",
  ],
  "home-garden": [
    "home",
    "furniture",
    "decor",
    "garden",
    "kitchen",
    "bedding",
    "pillow",
    "candle",
    "lamp",
    "rug",
    "curtain",
    "plant",
    "outdoor",
  ],
  "food-beverage": [
    "food",
    "coffee",
    "tea",
    "chocolate",
    "snack",
    "organic",
    "supplement",
    "drink",
    "beverage",
    "spice",
    "sauce",
    "gourmet",
  ],
  "health-wellness": [
    "health",
    "wellness",
    "vitamin",
    "supplement",
    "fitness",
    "yoga",
    "meditation",
    "cbd",
    "essential oil",
    "therapy",
    "natural",
  ],
  "sports-outdoors": [
    "sport",
    "gym",
    "workout",
    "running",
    "cycling",
    "camping",
    "hiking",
    "fishing",
    "outdoor",
    "athletic",
    "exercise",
  ],
  pets: [
    "pet",
    "dog",
    "cat",
    "puppy",
    "kitten",
    "animal",
    "collar",
    "leash",
    "treat",
    "grooming",
    "veterinary",
  ],
  "kids-baby": [
    "baby",
    "kid",
    "child",
    "toddler",
    "infant",
    "toy",
    "nursery",
    "maternity",
    "diaper",
    "stroller",
    "playroom",
  ],
  jewelry: [
    "jewelry",
    "ring",
    "necklace",
    "bracelet",
    "earring",
    "watch",
    "gold",
    "silver",
    "diamond",
    "pendant",
    "accessory",
    "accessories",
  ],
  automotive: [
    "car",
    "auto",
    "vehicle",
    "motorcycle",
    "truck",
    "parts",
    "tire",
    "motor",
    "garage",
    "driving",
  ],
  "arts-crafts": [
    "art",
    "craft",
    "handmade",
    "painting",
    "print",
    "canvas",
    "pottery",
    "crochet",
    "knitting",
    "sewing",
    "diy",
  ],
  "books-media": [
    "book",
    "ebook",
    "journal",
    "magazine",
    "music",
    "vinyl",
    "record",
    "game",
    "puzzle",
    "stationery",
  ],
  "business-services": [
    "business",
    "office",
    "software",
    "service",
    "consulting",
    "digital",
    "subscription",
    "saas",
    "agency",
    "professional",
  ],
  other: [],
};
